### ISSUE TITLE
records order mismatch

### ISSUE THREAD

**Issue by jazzl0ver** [sipwise/kamailio#5]
Hello,

For some reason, the order of records in the sip_capture table is incorrect (SIP 100 Trying recorded before the INVITE):
340396	2015-08-05 15:26:34	1438788394436624	100	1342217046_100270553@67.2x.5.112
340397	2015-08-05 15:26:34	1438788394436762	INVITE	1342217046_100270553@67.2x.5.112

Could you please tell me where to look at?

Kamailio is installed from this repo:
baseurl=http://download.opensuse.org/repositories/home:/kamailio:/v4.3.x-rpms/CentOS_6/

# rpm -qa|grep kama
kamailio-4.3.1-1.1.x86_64
kamailio-mysql-4.3.1-1.1.x86_64
kamailio-debuginfo-4.3.1-1.1.x86_64

Addon: I've checked with tcpdump - the packets come in correctly

**Comment by adubovikov** [comment]
this was fixed in the kamailio-dev. Please pull the last git.

https://github.com/kamailio/kamailio/

btw, homer repository is here:

https://github.com/sipcapture/

**Comment by jazzl0ver** [comment]
can you please send me a link to that commit? i tried to search for "siptrace" in closed issues and didn't find anything appropriate

**Comment by jazzl0ver** [comment]
"sipcapture" didn't show anything as well

**Comment by lmangani** [comment]
try filter by author adubovikov and you should find all commits

**Comment by jazzl0ver** [comment]
Any ideas when it's gonna appear in rpm packages?

**Comment by jazzl0ver** [comment]
lmangani, thank you!

**Comment by adubovikov** [comment]
better to ask the kamailio-dev directly
