### ISSUE TITLE
which webRTC client is used?

### ISSUE THREAD

**Issue by kossivi1984** [sipwise/kamailio#8]
Hello,
I am configuring kamailio MSRP relay and interconnected with a webRTC client. Which webRTC client is used, for performing the messages, sending the file, video call and screen sharing? Thank you for helping me if you have documents or link

**Comment by apogrebennyk** [comment]
Hi,
I don't really get your question, you can use one of the freely available clients like JsSIP or sipml5. Any standard client should work with Sipwise platform. For the questions related to kamailio features, please send your questions to the sr-users mailing list or in case of issues with one of its modules report it directly to https://github.com/kamailio/kamailio/issues

**Comment by kossivi1984** [comment]
Hello,
Can I have a configuration of JsSIP or sipml5 clients to see how interconnection is with kamailio?

**Comment by apogrebennyk** [comment]
Depends on your server configuration.. See for example http://kamailio.org/docs/modules/stable/modules/websocket.html
The WS server URL must point to the address where the xhttp module is ready to accept. But this is not the official kamailio mailing list and we do not support other kamailio installations here.

**Comment by kossivi1984** [comment]
Do you already have a kamailio configuration with the msrp connected to the JsSIP client or sipml5 to help me with? I can take inspiration from this configuration to be able to move forward

**Comment by apogrebennyk** [comment]
No, I don't.

**Comment by apogrebennyk** [comment]
You can however check what kamailio developers have published under https://github.com/kamailio/kamailio/blob/master/misc/examples/webrtc/websocket.cfg and the msrp module docs. Never used that.

**Comment by kossivi1984** [comment]
Hello,
this kamailio msrp websocket configuration work with jssip please ?
https://github.com/sipwise/kamailio/blob/master/misc/examples/webrtc/websocket.cfg

**Comment by apogrebennyk** [comment]
This is provided by kamailio.org "as is" and as an example, no guarantee.

**Comment by kossivi1984** [comment]
Hello,
Please, jsSIP support MSRP ?
